Добавляет декоративные элементы для каталога
htmlacademy-htmlcss/1902231-sedona-32 pull request #11
Opened 2021-11-14 18:32 UTC by anastasia-sp

2021-11-14 21:04 UTC, wrgraff requested changes

2021-11-15 11:31 UTC, anastasia-sp commented on styles/styles.css
> +.navigation-item .navigation-link-favourites {
Сделаем иконки независимыми!

2021-11-15 18:25 UTC, wrgraff commented on styles/styles.css
> +.navigation-item .navigation-link-favourites {
Осторожнее с лозунгами )

2021-11-15 19:19 UTC, wrgraff approved these changes

2021-11-15 19:19 UTC, wrgraff commented on styles/styles.css
> +  box-shadow: 0 0 0 3px #756257;
Кажется, это стили фокуса )
Там только у синей кнопки какая-то странная дурацкая рамка _вовнутрь_ при наведении.
А так просто там еще и в разных порядках статусы прописаны

2021-11-15 19:19 UTC, merged