Разметка главной страницы
htmlacademy-htmlcss/1902231-sedona-32 pull request #2
Opened 2021-09-27 16:47 UTC by anastasia-sp

2021-09-27 21:58 UTC, wrgraff requested changes
Как-будто постеснялась или побоялась классов накинуть =)
В принципе, это не критично. Ты все равно их поставишь в итоге, так как они нужны будут для оформления.

2021-09-27 21:58 UTC, wrgraff commented on .editorconfig
> +# на https://config.org и в разделе «Download a Plugin»
А это что? =)

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +            <a class="navigation-link" href="sedona.html">Главная</a>
Главная — это `index.html` =)

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +            <a class="navigation-link" href="about.html">О Седоне</a>
По условиям задания нам нужно ставить ссылки только для существующих страниц, для других нужно обойтись заглушками:

> - Если страница существует в макете, то на неё должна вести соответствующая ссылка, например, `<a href="catalog.html">`.
> - Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`.

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <a class="logo"><img src="" alt="Логотип сайта города Седона"></a>
Я рекомендую для хорошей читаемость вложенные теги на отдельной строке писать:
```suggestion
        <a class="logo">
          <img src="" alt="Логотип сайта города Седона">
        </a>
```

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +      <section> <!-- Здесь должен быть класс, да? -->
Рано или поздно он появится )

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <h1 class="visually-hidden">Город Седона</h1>
Во, выделила заголовок правильный, молодец

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <img src="" alt="Вид на красные скалы города Седона">
Скалы — это фоновая картинка.
А на переднем плане будет отдельная картинка, можно ее сделать контентной:
![изображение](https://user-images.githubusercontent.com/37917037/134987193-72ea0535-972e-4f92-9b53-36d5bcc2b658.png)

При чем, так как у нее текст прямо в содержании, можно прямо его и написать в `alt` — это будет очень логично

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +          заслуживающий большего!</h2> <!-- Или не нужно использовать <br>? -->
Я бы предложил пока не использовать `<br>`.

Дело в том, что форматированный текст ведет себя иначе, создавая ложное впечатление о своей ширине. А нам на этапе сеток нужно будет убедиться, что он подстраивается под сетку вне зависимости от форматирования. Может выйти и так, что если переносы убрать, то сетка совсем развалится.

Мы потом сможем поставить переносы, если это будет нужно (после модуля сеток).

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <h2>Седона — небольшой городок в Аризоне,<br>
На самом деле, на заголовок этот текст не тянет. Это скорее слоган, который больше дает эмоции. А вот содержимое секции он описывает не очень хорошо

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +              <ul class="advises-list">
Судя по форматированию кода, ты используешь какой-то форматтер (Prettier или Beautify, например).

Тебе нужно или разобраться с настройкой форматтеров, чтобы они делали 
код, соответствующий требованиям, или же пока что отключить их и 
поучиться оформлять код руками.

Да, это муторно, но прививает умение разбираться в том, как код должен 
выглядеть. А потом уже можно подключать всякие волшебные инструменты, которые 
будут оформлять код за тебя (ну и еще стоит отметить, то Prettier, например, разработан для форматирования js-кода, а не html).

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +          <li class="advantages-item">Настоящий городок
А как это `Настоящий городок` совсем без тега?
Он вообще-то намного больше заслуживает (прям как Седона)

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +                <li class="advise"> Жильё
Пространство имен не очень соблюдается. Было `advises-list`, а тут `advise`

Кстати, advise — это глагол. Немного странно выглядит =)

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <a href="catalog.html">Поиск гостиницы в Седоне</a>
Эта кнопка вызовет форму с подбором по дате заезда и выезда и прочее.
Но в каталоге страница другая, поэтому запасной страницей, на которую будет переход, если модальное окно не откроется, будет что-то еще.
Логичнее поставить заглушку все-таки (хотя я тоже сперва подумал, не подойдет ли страница каталога здесь. Но нет)

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +          <input type="email" placeholder="Ваш e-mail">
Инпуту обязательно нужен `<label>`

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +          <input type="email" placeholder="Ваш e-mail">
И еще ему нужен атрибут `name`, он без него не сможет отправлять данные

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +      <section>
Классов маловато =)
Вот почему чуть выше секшн имеет класс `hotel-search`, а здесь нет никакого.
Все равно понадобится, конечно, так что никуда от них не денешься, но все же

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +    <main class="main-index">
Почему именно main-`index`?

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +            <a class="button" href="https://twitter.com/htmlacademy_ru">
Почему класс `button`?
В лайве на Барбершопе так делали потому что в нем ссылки на соцсети выглядят так же, как и кнопки.
А у нас совсем не так, нам стили кнопки на этих ссылках будут совершенно лишними

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +      <section class="footer-social">
Секции без заголовков будут вызывать в валидаторе предупреждения.

Это логично: если мы использовали `<section>`, то значит это какой-то осмысленный блок информации. А раз он осмысленный, то и озаглавить его можно.

Поэтому, надо или избавиться от `<section>`, или добавить заголовок.

2021-09-27 21:58 UTC, wrgraff commented on index.html
> +        <p class="about-text"><a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a></p>
С точки зрения доступности для читающего сайт скринридером может быть не очень понятно, что именно ".html academy".
Видимо, это разработчик. Можно дописать это скрытым текстом, чтобы читалось как-то так: "Разработчик — .html academy"

2021-09-28 10:38 UTC, anastasia-sp commented on .editorconfig
> +# на https://config.org и в разделе «Download a Plugin»
Тут я ничего не трогала вообще, оно само!

2021-09-28 12:49 UTC, anastasia-sp commented on index.html
> +                <li class="advise"> Жильё
Ох уж эти коварные c и s :)

2021-09-28 16:26 UTC, wrgraff commented on .editorconfig
> +# на https://config.org и в разделе «Download a Plugin»
Так не бывает )

2021-09-28 17:47 UTC, wrgraff requested changes

2021-09-28 17:47 UTC, wrgraff commented on index.html
> +        </label>
Атрибуты `for` на лейбле и `id` на инпуте нужны тогда, когда их надо связать.
А связывать их нужно тогда, когда они рядом. Когда инпут вложен в лейбл, в этом уже нет необходимости:
```suggestion
        <label>
          <input type="email" name="e-mail" placeholder="Ваш e-mail">
        </label>
```

2021-09-28 17:47 UTC, wrgraff commented on index.html
> +        <label for="form-email">
Остается некоторая проблема: так как в лейбле текста нет (хоть сам лейбл и есть), то получается, что он все равно не подписан.
Можно использовать скрытый текст, если на макете такой подписи нет.

2021-09-28 17:47 UTC, wrgraff commented on index.html
> +          <a class="footer-social-item-icon" href="https://twitter.com/htmlacademy_ru">
Очень сложно, к тому же иконка — это вид, а на лайве Андрей рекомендовал опираться на логику.
По логике — это ссылка.
Проще и довольно понятно будет так:
```suggestion
          <a class="footer-social-link" href="https://twitter.com/htmlacademy_ru">
```

2021-09-28 18:41 UTC, anastasia-sp commented on .editorconfig
> +# на https://config.org и в разделе «Download a Plugin»
А, это я, наверное, скопировала так хорошо, половину вырезав. Верну на место)

2021-09-28 19:18 UTC, wrgraff approved these changes

2021-09-28 19:18 UTC, merged