Добавляет сетку на гридах
htmlacademy-htmlcss/1902231-sedona-32 pull request #9
Opened 2021-10-30 12:44 UTC by anastasia-sp

2021-10-31 11:53 UTC, wrgraff requested changes

2021-10-31 11:53 UTC, wrgraff commented on index.html
> +                <div class="advises-item-wrapper">
```suggestion
                <div class="advices-item-wrapper">
```

Только русскую не поставь =)

2021-10-31 11:53 UTC, wrgraff commented on index.html
> +                <div class="advises-item-wrapper">
Обертки во внешнем списке нужны в двух первых крупных пунктах.
В остальных трех необходимости в них нет, но ради единообразия можно оставить.

Обертки во внутреннем списке не настолько нужны.
Можно было бы сказать, что они нужны для единообразия, но тогда логично было бы сделать один и тот же класс для оберток и внешнего, и внутреннего списка

2021-10-31 11:53 UTC, wrgraff commented on index.html
> +        <div class="subscription-wrapper">
Можно и без обертки сверстать тут

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +.page-wrapper::after {
Это что-то странное. У `.page-wrapper` ведь нет псевдоэлементов.
`box-sizing` — не наследуемое свойство. Поэтому мы и задаем его для селекторов `*`, они выбирают "вообще все элементы".

```suggestion
*,
*::before,
*::after {
```

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  padding: 110px;
Как-то многовато

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  grid-row: 1/2;
Все эти `grid-column` и `grid-row` полезны далеко не всегда.
Ты "прибиваешь" элемент к определенной позиции, но есть ли в этом необходимость?

Предлагаю использовать для нужного количества колонок для картинки не конкретные линии, а просто описание количества колонок: `span 2`.

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  grid-row: 1/2;
Не забудь, что во втором элементе порядок картинки и текста другой.
Тоже гораздо изящнее будет решение с изменением порядка, а не привязка к линиям

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  grid-template-columns: 128px 800px 128px;
Сложно как-то )
Если хочешь сложное решение, сделай без обертки такую сетку, чтобы текст был ограничен по ширине, а поле с кнопкой занимало всю ширину сетки.

Скрин с подсказкой:
![изображение](https://user-images.githubusercontent.com/37917037/139581173-176c8b2e-3193-404c-a8ac-96b7609455d8.png)

Ну или можно простыми методами ширину ограничить

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  grid-template-columns: 540px 370px 50px 50px 50px;
Могут возникнуть проблемы с переполнением, если добавить еще один тип отображения карточек

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  display: grid;
Так, а зачем он нужен?

2021-10-31 11:53 UTC, wrgraff commented on catalog.html
> +            <a class="otel-card-image" href="#">
Букву потеряла
```suggestion
            <a class="hotel-card-image" href="#">
```

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  grid-template-columns: 230px 160px 520px 160px;
Неплохо разобралась.
Я бы еще `gap` добавил какой-то, чтобы элементы не слипались ни при каких обстоятельствах.
Можно (или придется) взять минимальный, например на базе расстояния между кнопками

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +  margin-right: 37px;
Не совпадает что-то:
![изображение](https://user-images.githubusercontent.com/37917037/139581580-37043352-c189-4744-82ee-345e0f1f057a.png)

2021-10-31 11:53 UTC, wrgraff commented on styles/styles.css
> +margin-right: 37px;
Этого класса нет у второй картинки. Надо разметку сделать идентичной — это обязательно.

И без него кстати все работает там =)
Так что отступ стоит убрать тоже. Но главное — разметка идентичная

2021-11-03 10:35 UTC, anastasia-sp commented on styles/styles.css
> +  display: grid;
Чтобы не схлопывались отступы

2021-11-03 10:35 UTC, anastasia-sp commented on styles/styles.css
> +  padding: 110px;
При меньших значениях получается несоответствие с макетом по расположению текста :(

2021-11-03 18:49 UTC, wrgraff commented on styles/styles.css
> +  padding: 110px;
Так оно и сейчас не по макету получается. В макете 3 строки текста, а у тебя 4.
А ты о каком несоответствии?

2021-11-04 17:01 UTC, wrgraff commented on styles/styles.css
> +  grid-column: span 1;
Он же и так будет одну колонку занимать )

2021-11-04 17:01 UTC, merged